# Generated by Django 5.1.3 on 2024-11-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_items_quantity_cart_items_cart_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='cart_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
