# Generated by Django 5.1.3 on 2024-11-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_items_cart_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_items',
            old_name='cart_count',
            new_name='quantity',
        ),
    ]
