# Generated by Django 5.1.3 on 2024-11-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_cart_count_cart_items_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='product_names',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
