# Generated by Django 5.1.3 on 2024-12-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_items_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
